CREATE TABLE "F8_DBA"."TEST_STUDENT" 
   (	
   "STUDENT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE  NOKEEP  NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50), 
	"DOB" DATE, 
	"TELUGU" NUMBER(*,0), 
	"ENGLISH" NUMBER(*,0), 
	"HINDI" NUMBER(*,0), 
	"MATHS" NUMBER(*,0), 
	"SCIENCE" NUMBER(*,0), 
	"SOCIAL" NUMBER(*,0), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	 CONSTRAINT "TEST_STUDENT_PK" PRIMARY KEY ("STUDENT_ID")  
   );
 
--===================================================================
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-Mon-YYYY HH24:MI:SS';
--=====================================================================

DECLARE 
 FIRST_NAME TEST_STUDENT.FIRST_NAME%TYPE;
 LAST_NAME TEST_STUDENT.LAST_NAME%TYPE;

 start_value integer := 1; 
 end_value integer := 500; 

 --Marks
 telugu_tmp integer;
 english_tmp integer;
 hindi_tmp integer;
 maths_tmp integer;
 science_tmp integer;
 social_tmp integer;

 year number;
 month number;
 day number;
 dob Date;
   
BEGIN

  FOR i IN start_value..end_value
  LOOP 
    select 'Duddukunta' || trunc(dbms_random.value(1,1000)),'Hari' || trunc(dbms_random.value(1,1000)),
	trunc(dbms_random.value(20,95)),trunc(dbms_random.value(20,90)),trunc(dbms_random.value(20,90)),trunc(dbms_random.value(20,98)),
	trunc(dbms_random.value(20,95)),trunc(dbms_random.value(20,90))
    INTO FIRST_NAME,LAST_NAME,telugu_tmp,english_tmp,hindi_tmp,maths_tmp,science_tmp,social_tmp from dual;    
  
  SELECT TO_DATE(
         TRUNC(
           DBMS_RANDOM.VALUE(
             TO_CHAR(DATE '1980-01-01','J'),
             TO_CHAR(DATE '2010-12-31','J')
           )
         ),
         'J'
       )
       + NUMTODSINTERVAL(
           FLOOR(DBMS_RANDOM.VALUE(0,86399)),
           'SECOND'
         ) AS dob_temp INTO dob
	FROM DUAL;
	DBMS_OUTPUT.PUT_LINE( 'Duddukunta' || FIRST_NAME ||'==='|| 'Hari' || LAST_NAME||'===DOB==='||dob
	||'===Telugu==='||telugu_tmp||'===english_tmp==='||english_tmp||'===hindi_tmp==='||hindi_tmp
	||'===maths_tmp==='||maths_tmp||'===science_tmp==='||science_tmp||'===social_tmp==='||social_tmp);
  
  INSERT INTO F8_DBA.TEST_STUDENT(FIRST_NAME,LAST_NAME,DOB,TELUGU,ENGLISH,HINDI,MATHS,SCIENCE,SOCIAL,CREATED_AT,UPDATED_AT) 
  values(FIRST_NAME,LAST_NAME,dob,telugu_tmp,english_tmp,hindi_tmp,maths_tmp,science_tmp,social_tmp,SYSTIMESTAMP,SYSTIMESTAMP);
  END LOOP;
END;
