DECLARE
	TYPE STUDENT_MARKS_REC IS RECORD(
		STUDENT_ID_TMP TEST_STUDENT.STUDENT_ID%TYPE,
		FIRST_NAME_TMP TEST_STUDENT.FIRST_NAME%TYPE,
		LAST_NAME_TMP TEST_STUDENT.LAST_NAME%TYPE,
		TELUGU_TMP TEST_STUDENT.TELUGU%TYPE, 
		ENGLISH_TMP TEST_STUDENT.ENGLISH%TYPE,
		HINDI_TMP TEST_STUDENT.HINDI%TYPE,
		MATHS_TMP TEST_STUDENT.MATHS%TYPE,
		SCIENCE_TMP TEST_STUDENT.SCIENCE%TYPE,
		SOCIAL_TMP TEST_STUDENT.SOCIAL%TYPE,	
		STUDENT_STATUS VARCHAR2(6),
		TOTAL_MARKS number,
		STUDENT_GRADE VARCHAR2(12),
		STUDENT_RANK number);
	TYPE STUDENT_REC IS TABLE OF STUDENT_MARKS_REC;
	STUDENT_REC_TMP STUDENT_REC;
	TOTAL_MARKS INTEGER :=0;
	STUDENT_RANK INTEGER :=0;
	STUDENT_GRADE VARCHAR2(12);
	STUDENT_STATUS VARCHAR2(6);

	STUDENT_TMP STUDENT_REC := STUDENT_REC();

BEGIN
	SELECT STUDENT_ID,FIRST_NAME,LAST_NAME,TELUGU,ENGLISH,HINDI,MATHS,SCIENCE,SOCIAL,null,
	(TELUGU+ENGLISH+HINDI+MATHS+SCIENCE+SOCIAL) AS TOTAL_MARKS,null,
	DENSE_RANK() OVER (ORDER BY (TELUGU+ENGLISH+HINDI+MATHS+SCIENCE+SOCIAL))	
	BULK COLLECT INTO STUDENT_REC_TMP FROM TEST_STUDENT WHERE TELUGU >=70 ORDER BY STUDENT_ID ;

	--DBMS_OUTPUT.PUT_LINE(STUDENT_REC_TMP.count);
  	FOR i IN STUDENT_REC_TMP.FIRST..STUDENT_REC_TMP.LAST
  	LOOP
	  	TOTAL_MARKS := STUDENT_REC_TMP(i).TOTAL_MARKS;
	    STUDENT_RANK := STUDENT_REC_TMP(i).STUDENT_RANK;
	  	--DBMS_OUTPUT.PUT_LINE('TOTAL MARKS:='||TOTAL_MARKS);
	  	IF  		  	
		  	STUDENT_REC_TMP(i).TELUGU_TMP >= 35 
		  	and STUDENT_REC_TMP(i).ENGLISH_TMP >= 35 
		  	and STUDENT_REC_TMP(i).HINDI_TMP >= 20 
		  	and STUDENT_REC_TMP(i).MATHS_TMP >= 35 
		  	and STUDENT_REC_TMP(i).SCIENCE_TMP >= 35 
		  	and STUDENT_REC_TMP(i).SOCIAL_TMP >= 35 
		 THEN 
		 	STUDENT_STATUS := 'Passed';			
		 	IF	TOTAL_MARKS >= 250 AND TOTAL_MARKS <= 299
			 	THEN STUDENT_GRADE := 'THIRD';
		 	ELSIF 
    			TOTAL_MARKS >= 300 AND TOTAL_MARKS <= 359
    		THEN
    			STUDENT_GRADE := 'SECOND';
    		ELSIF 
    			TOTAL_MARKS >= 360 AND TOTAL_MARKS <= 419
    		THEN
    			STUDENT_GRADE := 'FIRST';
    		ELSIF 
    			TOTAL_MARKS >= 420 AND TOTAL_MARKS <= 479
    		THEN
    			STUDENT_GRADE := 'DISTINCTION';
    		ELSIF 
    			TOTAL_MARKS <= 480
    		THEN
    			STUDENT_GRADE := 'TOPPER';
		 	END IF;    		
    	ELSIF 
    		STUDENT_REC_TMP(i).SOCIAL_TMP >= 351 
    	THEN
    		DBMS_OUTPUT.PUT_LINE('Never Executes');
    	ELSE
    		STUDENT_STATUS := 'Failed';
	    	STUDENT_GRADE := 'Failed';
	    	STUDENT_RANK := 0;
    	END IF;
    
    	DBMS_OUTPUT.PUT_LINE('STUDENT_STATUS:='||STUDENT_STATUS
    		||'==STUDENT_GRADE:='||STUDENT_GRADE
    		||'==TOTAL_MARKS:='||STUDENT_REC_TMP(i).TOTAL_MARKS
    		||'==STUDENT_RANK:='||STUDENT_RANK);
    	STUDENT_TMP.extend;
    	STUDENT_TMP(STUDENT_TMP.last).STUDENT_ID_TMP := STUDENT_REC_TMP(i).STUDENT_ID_TMP;
    	STUDENT_TMP(STUDENT_TMP.last).FIRST_NAME_TMP := STUDENT_REC_TMP(i).FIRST_NAME_TMP;
   		STUDENT_TMP(STUDENT_TMP.last).LAST_NAME_TMP := STUDENT_REC_TMP(i).LAST_NAME_TMP;
  		STUDENT_TMP(STUDENT_TMP.last).TELUGU_TMP := STUDENT_REC_TMP(i).TELUGU_TMP;
 		STUDENT_TMP(STUDENT_TMP.last).ENGLISH_TMP := STUDENT_REC_TMP(i).ENGLISH_TMP; 	
 		STUDENT_TMP(STUDENT_TMP.last).HINDI_TMP := STUDENT_REC_TMP(i).HINDI_TMP;
   		STUDENT_TMP(STUDENT_TMP.last).MATHS_TMP := STUDENT_REC_TMP(i).MATHS_TMP;
  		STUDENT_TMP(STUDENT_TMP.last).SCIENCE_TMP := STUDENT_REC_TMP(i).SCIENCE_TMP;
 		STUDENT_TMP(STUDENT_TMP.last).SOCIAL_TMP := STUDENT_REC_TMP(i).SOCIAL_TMP; 	
 		STUDENT_TMP(STUDENT_TMP.last).STUDENT_STATUS := STUDENT_STATUS;
 		STUDENT_TMP(STUDENT_TMP.last).TOTAL_MARKS := TOTAL_MARKS;
 		STUDENT_TMP(STUDENT_TMP.last).STUDENT_GRADE := STUDENT_GRADE; 	
	 	STUDENT_TMP(STUDENT_TMP.last).STUDENT_RANK := STUDENT_RANK; 	
 	
  	END LOOP;
 
END;
