CREATE TABLE sales_order_info(
    sales_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Region VARCHAR2(50) NOT NULL,
    Country VARCHAR2(50) NOT NULL,
	Item_Type varchar2(50),
	Sales_Channel varchar2(50),
	Order_Priority char(1),
	Order_Date timestamp,
	Order_ID number(20,0),
	Ship_Date timestamp,
	Units_Sold number,
	Unit_Price number(20,5),
	Unit_Cost number(20,5),
	Total_Revenue number(20,5),
	Total_Cost number(20,5),
	Total_Profit number(20,5),
    CONSTRAINT sales_id_PK PRIMARY KEY(sales_id)
);