SELECT emp.EMPLOYEE_ID,emp.FIRST_NAME,mngr.EMPLOYEE_ID,mngr.FIRST_NAME
FROM ORACLE_DEMO.EMPLOYEE_MANAGER emp INNER JOIN ORACLE_DEMO.EMPLOYEE_MANAGER mngr
ON emp.MANAGER_ID = mngr.EMPLOYEE_ID ;

SELECT emp.EMPLOYEE_ID,emp.FIRST_NAME,mngr.EMPLOYEE_ID mngr,mngr.FIRST_NAME
FROM ORACLE_DEMO.EMPLOYEE_MANAGER emp,ORACLE_DEMO.EMPLOYEE_MANAGER mngr
WHERE emp.MANAGER_ID = MNGR.EMPLOYEE_ID ORDER BY mngr;

select emp.EMPLOYEE_ID,emp.FIRST_NAME,mngr.EMPLOYEE_ID MANAGER_ID ,mngr.FIRST_NAME Manager_name
FROM ORACLE_DEMO.EMPLOYEE_MANAGER emp left join ORACLE_DEMO.EMPLOYEE_MANAGER mngr
ON emp.MANAGER_ID = mngr.EMPLOYEE_ID ORDER BY EMP.EMPLOYEE_ID ;