CREATE TABLE student_info(
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_name VARCHAR2(50) NOT NULL,
    father_name VARCHAR2(50) NOT NULL,
	gender varchar2(10),
	MOBILE long,
	CATEGORY varchar2(20),
    CONSTRAINT student_id_PK PRIMARY KEY(student_id)
);

select * from student_info where
(upper(GENDER)='FEMALE' and CATEGORY not in ('SC','ST') OR upper(GENDER)='MALE' and CATEGORY not in ('OC','BC-C','BC-D','SC'));